name: jamesransom.nyc
favicon: null
layout_spectrum: 0.09058
typography_spectrum: 0.38914
title: James Ransom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9bb8ca'
    - '#0b0a10'
    - '#54554f'
    - '#590004'
    - '#d0701f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
